<?php

declare(strict_types=1);

namespace PoP\APIEndpointsForWP;

class Environment
{
    public const DISABLE_GRAPHQL_API_ENDPOINT = 'DISABLE_GRAPHQL_API_ENDPOINT';
    public const GRAPHQL_API_ENDPOINT = 'GRAPHQL_API_ENDPOINT';
    public const DISABLE_REST_API_ENDPOINT = 'DISABLE_REST_API_ENDPOINT';
    public const REST_API_ENDPOINT = 'REST_API_ENDPOINT';
    public const DISABLE_NATIVE_API_ENDPOINT = 'DISABLE_NATIVE_API_ENDPOINT';
    public const NATIVE_API_ENDPOINT = 'NATIVE_API_ENDPOINT';
}
